### ISSUE TITLE
Does not work with Solidity v0.8.18 named mapping parameters

### ISSUE THREAD

**Issue by PaulRBerg** [ConsenSysDiligence/solidity-metrics#11]
Solidity v0.8.18 added support for a killer feature: [named mapping parameters](https://twitter.com/PaulRBerg/status/1621949932608360453).

We can now define mappings like this:

```solidity
contract Foo {
    mapping(address key => uint256 value) public items;
}
```

However, running `solidity-code-metrics` over a code base that contains named mapping parameters produces an error like this:

<details>
<summary>Click me to see error</summary>

```javascript
Error found while parsing the following file: ./src/Foo.sol

ParserError: extraneous input 'key' expecting '=>' (5:20)
    at Object.parse (/Users/paulrberg/.fnm/node-versions/v18.12.1/installation/lib/node_modules/solidity-code-metrics/node_modules/surya/node_modules/@solidity-parser/parser/dist/index.cjs.js:36973:11)
    at /Users/paulrberg/.fnm/node-versions/v18.12.1/installation/lib/node_modules/solidity-code-metrics/node_modules/surya/lib/graph.js:86:23
    at _loop (/Users/paulrberg/.fnm/node-versions/v18.12.1/installation/lib/node_modules/solidity-code-metrics/node_modules/surya/lib/graph.js:95:6)
    at Object.graph (/Users/paulrberg/.fnm/node-versions/v18.12.1/installation/lib/node_modules/solidity-code-metrics/node_modules/surya/lib/graph.js:221:18)
    at SolidityMetricsContainer.getDotGraphs (/Users/paulrberg/.fnm/node-versions/v18.12.1/installation/lib/node_modules/solidity-code-metrics/src/metrics/metrics.js:107:45)
    at Object.<anonymous> (/Users/paulrberg/.fnm/node-versions/v18.12.1/installation/lib/node_modules/solidity-code-metrics/src/cli.js:44:25)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12) {
  errors: [
    {
      message: "extraneous input 'key' expecting '=>'",
      line: 5,
      column: 20
    },
    {
      message: "extraneous input 'value' expecting ')'",
      line: 5,
      column: 35
    }
  ]
}
```

</details>

**Comment by tintinweb** [comment]
should be fixed with new release (https://github.com/Consensys/solidity-metrics/commit/dab89b62ee488469dc86a8c0a6e8598104cdefcb)

**Comment by hexpaydaydev** [comment]
while it no longer errs, it does still log out unnecessarily verbosely: 
```
Error found while parsing the following file: ./contracts/AuthorizationManager.sol

ParserError: extraneous input 'key' expecting '=>' (18:18)
    at Object.parse (~/stake-manager/node_modules/surya/node_modules/@solidity-parser/parser/dist/index.cjs.js:36973:11)
    at ~/stake-manager/node_modules/surya/lib/mdreport.js:60:23
    at _loop (~/stake-manager/node_modules/surya/lib/mdreport.js:69:6)
    at Object.mdreport (~/stake-manager/node_modules/surya/lib/mdreport.js:185:18)
    at SolidityMetricsContainer.generateReportMarkdown (~/stake-manager/node_modules/solidity-code-metrics/src/metrics/metrics.js:204:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errors: [
    {
      message: "extraneous input 'key' expecting '=>'",
      line: 18,
      column: 18
    },
    {
      message: "extraneous input 'settings' expecting ')'",
      line: 18,
      column: 33
    }
  ]
}
```
